version: "3"
services:
    tileserver:
        image: maptiler/tileserver-gl:latest
        container_name: tileserver
        command: "--verbose -p 4545 -c config.json"
        volumes:
          - $PWD/tileserver-data:/data
        ports:
          - "4545:4545"
